# Generated by Django 5.0.6 on 2024-05-21 21:49

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
