# Generated by Django 5.0.6 on 2024-05-25 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nombre_producto_nombre_remove_empleado_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
