# Generated by Django 5.0.6 on 2024-05-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_categoria_producto_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tipoherramienta',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
